name: Evaluate site performance
on: push
jobs:
  lighthouse:
    name: Evaluating site performance with Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.4.4
        with:
          version:  15.x

      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install Ubuntu dependencies for node-canvas
        run: sudo apt-get -y install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build site
        working-directory: ./site
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Run Lighthouse CI
        working-directory: ./site
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: |
          npm install -g @lhci/cli@0.4.x
          lhci autorun --collect.staticDistDir=site/
