name: Cypress e2e tests
on: [push, pull_request]
jobs:
  test:
    name: Running e2e tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3
        with:
          node-version:  18.x

      - name: Set up rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: '1.64.0'

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Yarn install
        working-directory: ./site
        run: |
          yarn install --frozen-lockfile

      - name: Run tests
        working-directory: ./site
        env:
          TERM: dumb
        run: |
          yarn test:serve &
          until $(curl --silent --fail http://localhost:8080/summer2021 | grep QuACS --silent); do printf '.'; sleep 1; done
          yarn test:e2e:headless
